version: "3.3" # compose file version
networks: # for creating network
  skill-portal-bridge: # name of bridge it will auto matically choose subnet

services:
  skill-portal-server:
    build: .
    container_name: ZITNAUT
    ports:
      - "9090:8080"
    networks:
      - skill-portal-bridge
    depends_on:
      - skill-portal-db

    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-docker:3306/skill-enhancement-portal?autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_HOST: mysql-docker
      MYSQL_PORT: 3306
    restart: always

  skill-portal-db:
    container_name: mysql-docker
    image: mysql:latest
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    hostname: mysql-docker
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-docker:3306/skill-enhancement-portal?autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: skill-enhancement-portal
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3307:3306"
    networks:
      - skill-portal-bridge

  skill-portal-client: # name of app
    container_name: CLIENT
    build: ../skill-enhancement-portal-client/

    ports:
      - '80:80'
    networks: # using network
      - skill-portal-bridge
    restart: always

volumes:
  db_data: {}

